config/routes.rb
Rails.application.routes.draw do
  resources :documentaryfilms
  resources :series, as: 'series'
  resources :movies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentaryfilm.rb
class Documentaryfilm < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentaryfilms_controller.rb
class DocumentaryfilmsController < ApplicationController
  before_action :set_documentaryfilm, only: %i[ show edit update destroy ]

  # GET /documentaryfilms or /documentaryfilms.json
  def index
    @documentaryfilms = Documentaryfilm.all
  end

  # GET /documentaryfilms/1 or /documentaryfilms/1.json
  def show
  end

  # GET /documentaryfilms/new
  def new
    @documentaryfilm = Documentaryfilm.new
  end

  # GET /documentaryfilms/1/edit
  def edit
  end

  # POST /documentaryfilms or /documentaryfilms.json
  def create
    @documentaryfilm = Documentaryfilm.new(documentaryfilm_params)

    respond_to do |format|
      if @documentaryfilm.save
        format.html { redirect_to documentaryfilm_url(@documentaryfilm), notice: "Documentaryfilm was successfully created." }
        format.json { render :show, status: :created, location: @documentaryfilm }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @documentaryfilm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documentaryfilms/1 or /documentaryfilms/1.json
  def update
    respond_to do |format|
      if @documentaryfilm.update(documentaryfilm_params)
        format.html { redirect_to documentaryfilm_url(@documentaryfilm), notice: "Documentaryfilm was successfully updated." }
        format.json { render :show, status: :ok, location: @documentaryfilm }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @documentaryfilm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documentaryfilms/1 or /documentaryfilms/1.json
  def destroy
    @documentaryfilm.destroy

    respond_to do |format|
      format.html { redirect_to documentaryfilms_url, notice: "Documentaryfilm was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_documentaryfilm
      @documentaryfilm = Documentaryfilm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def documentaryfilm_params
      params.require(:documentaryfilm).permit(:name, :synopsis, :director)
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :synopsis, :director)
    end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    @series = Serie.all
  end

  # GET /series/new
  def new
    @serie = Serie.new
  end

  # POST /series or /series.json
  def create
    @serie = Serie.new(series_params)

    respond_to do |format|
      if @serie.save
        format.html { redirect_to series_index_url(@serie), notice: "Serie was successfully created." }
        format.json { render :show, status: :created, location: @serie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @serie.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @serie = Serie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:serie).permit(:name, :synopsis, :director)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentaryfilms_helper.rb
module DocumentaryfilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/documentaryfilms/_documentaryfilm.html.erb
<div id="<%= dom_id documentaryfilm %>">
  <tr>  
    <th scope="row"><%= documentaryfilm.id %></th>
    <td><%= documentaryfilm.name %></td>
    <td><%= documentaryfilm.synopsis %></td>
    <td><%= documentaryfilm.director %></td>
  </tr>

</div> 

app/views/documentaryfilms/_form.html.erb
<%= form_with(model: documentaryfilm) do |form| %>
  <% if documentaryfilm.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(documentaryfilm.errors.count, "error") %> prohibited this documentaryfilm from being saved:</h2>

      <ul>
        <% documentaryfilm.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :synopsis, style: "display: block" %>
    <%= form.text_field :synopsis %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/documentaryfilms/edit.html.erb
<h1>Editing documentaryfilm</h1>

<%= render "form", documentaryfilm: @documentaryfilm %>

<br>

<div>
  <%= link_to "Show this documentaryfilm", @documentaryfilm %> |
  <%= link_to "Back to documentaryfilms", documentaryfilms_path %>
</div>

app/views/documentaryfilms/index.html.erb
<h1>Documentales</h1>
<div  class= "new">
<%= link_to "Ingresar Documental", new_documentaryfilm_path, class: 'btn btn-primary' %>
</div>

<div id="movies-container" class="container">

<div id="documentaryfilm">
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Synopsis</th>
      <th scope="col">Director</th>
    </tr>
  </thead>
  <tbody>
    <% @documentaryfilms.each do |documentaryfilm| %>
        <%= render documentaryfilm %>
      <% end %>
    
  </tbody>
</table>

</div>

app/views/documentaryfilms/new.html.erb
<h1>New documentaryfilm</h1>

<%= render "form", documentaryfilm: @documentaryfilm %>

<br>

<div>
  <%= link_to "Back to documentaryfilms", documentaryfilms_path %>
</div>

app/views/documentaryfilms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @documentaryfilm %>

<div>
  <%= link_to "Edit this documentaryfilm", edit_documentaryfilm_path(@documentaryfilm) %> |
  <%= link_to "Back to documentaryfilms", documentaryfilms_path %>

  <%= button_to "Destroy this documentaryfilm", @documentaryfilm, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WOW CINE</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  
  <div class="container">
  
    <%= yield %>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :synopsis, style: "display: block" %>
    <%= form.text_field :synopsis %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
  <tr>  
    <th scope="row"><%= movie.id %></th>
    <td><%= movie.name %></td>
    <td><%= movie.synopsis %></td>
    <td><%= movie.director %></td>
  </tr>

</div> 

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<h1>Peliculas</h1>
<div  class= "new">
<%= link_to "Ingresar Película", new_movie_path, class: 'btn btn-primary' %>
</div>

<div id="movies-container" class="container">

<div id="movies">
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Synopsis</th>
      <th scope="col">Director</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
        <%= render movie %>
      <% end %>
    
  </tbody>
</table>

</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>

  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>

app/views/series/_form.html.erb
<%= form_with model: serie, url: series_index_path do |form| %>
  <% if serie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(serie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% serie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div>
  <%= form.label :name, style: "display: block" %>
  <%= form.text_field :name %>
</div>

<div>
  <%= form.label :synopsis, style: "display: block" %>
  <%= form.text_field :synopsis %>
</div>

<div>
  <%= form.label :director, style: "display: block" %>
  <%= form.text_field :director %>
</div>

<div>
  <%= form.submit %>
</div>
<% end %>

app/views/series/_serie.html.erb
<div id="<%= dom_id serie %>">
  <tr>  
    <th scope="row"><%= serie.id %></th>
    <td><%= serie.name %></td>
    <td><%= serie.synopsis %></td>
    <td><%= serie.director %></td>
  </tr>

</div> 

app/views/series/edit.html.erb
<h1>Editing serie</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Show this serie", @series %> |
  <%= link_to "Back to series", series_path %>
</div>

app/views/series/index.html.erb
<h1>Series</h1>
<div  class= "new">
<%= link_to "Ingresar Serie", new_series_path, class: 'btn btn-primary' %>
</div>

<div id="movie-container" class="container">

<div id="series">
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Synopsis</th>
      <th scope="col">Director</th>
    </tr>
  </thead>
  <tbody>
    <% @series.each do |serie| %>
        <%= render serie %>
      <% end %>
    
  </tbody>
</table>

</div>

app/views/series/new.html.erb
<h1>New serie</h1>

<%= render "form", serie: @serie %>

<br>

<div>
  <%= link_to "Back to series", series_index_path %>
</div>

app/views/series/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @series %>

<div>
  <%= link_to "Edit this serie", edit_series_path(@series) %> |
  <%= link_to "Back to series", series_path %>

  <%= button_to "Destroy this serie", @series, method: :delete %>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div style="text-align: center;">
    <h6 id="logo">WOW CINE INC., | COPYRIGHT OF JOSECH </h6>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav id="menutop" class="navbar navbar-dark bg-dark navbar-expand-lg">
  <div class="container">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", alt: "LOGO", class: "logo-image" %>
  <% end %>
  
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
          <ul class="navbar-nav ms-auto">
              
              <li class="nav-item">
                <%= link_to 'Home', root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
              <%= link_to 'Series', series_index_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
              <%= link_to 'Peliculas', movies_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
              <%= link_to 'Documentales', documentaryfilms_path, class: 'nav-link' %>
                  </li>
          </ul>
      </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<section>
  <div class="container">
    <h1 class="recetas-titulo">WOW CINE</h1>
    <div class="row justify-content-center">
      <div class="col-12 col-sm-12 col-md-4 col-lg-4">
        <div class="card">
          <%= image_tag "series", alt: "SERIES", width: '180', height: '250', class: 'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title" id="series">SERIES</h5>
            <p class="card-text" id="card-texto">¡Sumérgete en el mundo de las series! donde la emoción nunca termina.</p>
            <%= link_to series_index_path, class: "btn btn-primary" do %>
              Ver Cartelera
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-12 col-md-4 col-lg-4">
        <div class="card">
          <%= image_tag "peliculas", alt: "PELICULAS", width: '180', height: '250', class: 'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title" id="tiramisu">PELICULAS</h5>
            <p class="card-text" id="card-texto">¡La magia del cine te envuelve aquí! Cada película es una aventura inolvidable.</p>
            <%= link_to movies_path, class: "btn btn-primary" do %>
              Ver Cartelera
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-12 col-md-4 col-lg-4">
        <div class="card">
          <%= image_tag "documentales", alt: "DOCUMENTALES", width: '180', height: '250', class: 'card-img-top' %>
          <div class="card-body">
            <h5 class="card-title" id="documentales">DOCUMENTALES</h5>
            <p class="card-text" id="card-texto">Descubre la realidad en su máxima expresión, aprendiendo con las historias del mundo real.</p>
            <%= link_to documentaryfilms_path, class: "btn btn-primary" do %>
              Ver Cartelera
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>